<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('restaurants', function (Blueprint $table) {
            $table->text('ai_description')->nullable()->after('description')
                  ->comment('SEO-optimized description generated by AI. Falls back to description if null.');
            $table->timestamp('ai_description_generated_at')->nullable()->after('ai_description');
        });
    }

    public function down(): void
    {
        Schema::table('restaurants', function (Blueprint $table) {
            $table->dropColumn(['ai_description', 'ai_description_generated_at']);
        });
    }
};
