<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::table('restaurants', function (Blueprint $table) {
            $table->text('ai_description_en')->nullable()->after('ai_description_generated_at')
                  ->comment('SEO-optimized English description generated by AI.');
            $table->timestamp('ai_description_en_generated_at')->nullable()->after('ai_description_en');
        });
    }

    public function down(): void
    {
        Schema::table('restaurants', function (Blueprint $table) {
            $table->dropColumn(['ai_description_en', 'ai_description_en_generated_at']);
        });
    }
};
