#!/usr/bin/env python3
"""
Migrate analytics_events from SQLite backup to MySQL.
Generates batched INSERT IGNORE SQL. Safe to re-run.
"""

import sqlite3
import os
import sys
import json

SQLITE_PATH = "/Users/javier/WebsProjects/_backups_previos/restaurantesmexicanos/database/database.sqlite"
OUTPUT_SQL = "/tmp/famer_analytics_migration.sql"
BATCH_SIZE = 500  # smaller batches for large rows (user_agent is TEXT)

COLS = [
    'id', 'restaurant_id', 'event_type', 'user_type', 'user_id',
    'ip_address', 'user_agent', 'referrer', 'device_type', 'browser',
    'platform', 'country_code', 'city', 'region', 'metadata',
    'session_id', 'created_at', 'updated_at',
]

def escape_str(val):
    if val is None:
        return 'NULL'
    val = str(val).replace('\\', '\\\\').replace("'", "\\'").replace('\0', '')
    return f"'{val}'"

def format_val(col, val):
    if val is None:
        return 'NULL'
    if isinstance(val, int):
        return str(val)
    if isinstance(val, float):
        return str(val)
    return escape_str(val)

def main():
    if not os.path.exists(SQLITE_PATH):
        print(f"ERROR: SQLite not found at {SQLITE_PATH}")
        sys.exit(1)

    conn = sqlite3.connect(SQLITE_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    cursor.execute("SELECT COUNT(*) FROM analytics_events")
    total = cursor.fetchone()[0]
    print(f"Total analytics events: {total:,}")
    print(f"Output: {OUTPUT_SQL}")

    cols_str = ', '.join(f'`{c}`' for c in COLS)
    select_str = ', '.join(f'`{c}`' for c in COLS)
    cursor.execute(f"SELECT {select_str} FROM analytics_events ORDER BY id")

    rows_written = 0
    batch = []

    with open(OUTPUT_SQL, 'w', encoding='utf-8') as f:
        f.write("-- FAMER analytics_events migration from SQLite backup\n")
        f.write("-- Generated by migrate_analytics_to_mysql.py\n")
        f.write("-- 1.15M events from Nov 2025 - Mar 1, 2026\n\n")
        f.write("SET NAMES utf8mb4;\n")
        f.write("SET foreign_key_checks = 0;\n\n")

        def write_batch(b):
            if not b:
                return
            values_str = ',\n  '.join(b)
            f.write(f"INSERT IGNORE INTO `analytics_events` ({cols_str}) VALUES\n  {values_str};\n\n")

        for row in cursor:
            row_dict = dict(zip(COLS, row))
            values = [format_val(col, row_dict[col]) for col in COLS]
            batch.append(f"({', '.join(values)})")
            rows_written += 1

            if len(batch) >= BATCH_SIZE:
                write_batch(batch)
                batch = []
                if rows_written % 50000 == 0:
                    print(f"  {rows_written:,}/{total:,} processed...")

        write_batch(batch)
        f.write("SET foreign_key_checks = 1;\n")

    print(f"\nDone! {rows_written:,} rows written to {OUTPUT_SQL}")
    size_mb = os.path.getsize(OUTPUT_SQL) / (1024 * 1024)
    print(f"File size: {size_mb:.1f} MB")
    conn.close()

if __name__ == '__main__':
    main()
