#!/usr/bin/env python3
"""
Migrate restaurants from SQLite backup to MySQL on VPS.
Generates batched INSERT IGNORE SQL file for safe re-runs.
"""

import sqlite3
import os
import sys

SQLITE_PATH = "/Users/javier/WebsProjects/_backups_previos/restaurantesmexicanos/database/database.sqlite"
OUTPUT_SQL = "/tmp/famer_restaurants_migration.sql"
BATCH_SIZE = 200

# Columns that exist in SQLite but NOT in MySQL (exclude them)
SQLITE_ONLY_COLS = {
    'avg_service_rating', 'avg_food_rating', 'avg_ambiance_rating',
    'claim_reminder_sent_at', 'claim_reminder_type', 'welcome_email_sent_at',
    'famer_email_1_sent_at', 'famer_email_2_sent_at', 'famer_email_3_sent_at',
    'yelp_photos',
    'logo',  # SQLite has both image AND logo; MySQL only has image, so skip logo
}

# status='closed' is not a valid MySQL enum value
STATUS_MAP = {
    'closed': 'rejected',
    'approved': 'approved',
    'pending': 'pending',
    'rejected': 'rejected',
}

def escape_str(val):
    """Escape a string value for MySQL INSERT."""
    if val is None:
        return 'NULL'
    # Escape backslashes first, then single quotes
    val = str(val).replace('\\', '\\\\').replace("'", "\\'").replace('\0', '')
    return f"'{val}'"

def format_val(col, val):
    """Format a value for MySQL, handling special cases."""
    if val is None:
        return 'NULL'

    # Handle status enum mapping
    if col == 'status':
        mapped = STATUS_MAP.get(str(val), 'pending')
        return f"'{mapped}'"

    # Integers and floats: no quotes
    if isinstance(val, int):
        return str(val)
    if isinstance(val, float):
        return str(val)

    # Everything else: string escape
    return escape_str(val)

def main():
    if not os.path.exists(SQLITE_PATH):
        print(f"ERROR: SQLite not found at {SQLITE_PATH}")
        sys.exit(1)

    conn = sqlite3.connect(SQLITE_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    # Get SQLite column names
    cursor.execute("PRAGMA table_info(restaurants)")
    sqlite_cols = [row[1] for row in cursor.fetchall()]

    # Build column mapping: SQLite col -> MySQL col
    col_map = {}
    for col in sqlite_cols:
        if col in SQLITE_ONLY_COLS:
            continue
        col_map[col] = col

    sqlite_select_cols = list(col_map.keys())
    mysql_insert_cols = [col_map[c] for c in sqlite_select_cols]

    # MySQL columns as backtick-quoted string
    cols_str = ', '.join(f'`{c}`' for c in mysql_insert_cols)

    print(f"Migrating {len(sqlite_select_cols)} columns")
    print(f"Output: {OUTPUT_SQL}")

    # Count total
    cursor.execute("SELECT COUNT(*) FROM restaurants")
    total = cursor.fetchone()[0]
    print(f"Total restaurants in SQLite: {total}")

    select_cols_str = ', '.join(f'`{c}`' for c in sqlite_select_cols)
    cursor.execute(f"SELECT {select_cols_str} FROM restaurants ORDER BY id")

    rows_written = 0
    batch = []

    with open(OUTPUT_SQL, 'w', encoding='utf-8') as f:
        f.write("-- FAMER restaurants migration from SQLite backup\n")
        f.write("-- Generated by migrate_sqlite_to_mysql.py\n")
        f.write("-- Safe to re-run: uses INSERT IGNORE (skips duplicate slugs)\n\n")
        f.write("SET NAMES utf8mb4;\n")
        f.write("SET foreign_key_checks = 0;\n\n")

        def write_batch(b):
            if not b:
                return
            values_str = ',\n  '.join(b)
            f.write(f"INSERT IGNORE INTO `restaurants` ({cols_str}) VALUES\n  {values_str};\n\n")

        for row in cursor:
            row_dict = dict(zip(sqlite_select_cols, row))
            values = [format_val(sqlite_col, row_dict[sqlite_col]) for sqlite_col in sqlite_select_cols]
            batch.append(f"({', '.join(values)})")
            rows_written += 1

            if len(batch) >= BATCH_SIZE:
                write_batch(batch)
                batch = []
                if rows_written % 2000 == 0:
                    print(f"  {rows_written}/{total} processed...")

        write_batch(batch)

        f.write("SET foreign_key_checks = 1;\n")

    print(f"\nDone! {rows_written} rows written to {OUTPUT_SQL}")
    size_mb = os.path.getsize(OUTPUT_SQL) / (1024 * 1024)
    print(f"File size: {size_mb:.1f} MB")

    conn.close()

if __name__ == '__main__':
    main()
