#!/usr/bin/env python3
"""
Migrate multiple tables from SQLite backup to MySQL.
Generates batched INSERT IGNORE SQL. Safe to re-run.
"""

import sqlite3
import os
import sys

SQLITE_PATH = "/Users/javier/WebsProjects/_backups_previos/restaurantesmexicanos/database/database.sqlite"
OUTPUT_SQL = "/tmp/famer_tables_migration.sql"
BATCH_SIZE = 500

# Tables to migrate with their columns (in order)
TABLES = {
    'features': ['id','name','slug','icon','category','is_active','sort_order','created_at','updated_at'],
    'food_tags': ['id','name','slug','icon','is_active','created_at','updated_at'],
    'users': ['id','name','email','email_verified_at','password','remember_token','created_at',
              'updated_at','role','phone','last_login_at','reminder_sent_at','referral_code',
              'referred_by','sms_marketing_consent','sms_consent_at','sms_opted_out_at'],
    'reviews': ['id','restaurant_id','user_id','name','email','rating','comment','status',
                'is_active','created_at','updated_at','title','helpful_count','not_helpful_count',
                'approved_at','ip_address','user_agent','owner_response','owner_response_by',
                'owner_response_at','is_verified','check_in_id'],
    'media': ['id','model_type','model_id','uuid','collection_name','name','file_name',
              'mime_type','disk','conversions_disk','size','manipulations','custom_properties',
              'generated_conversions','responsive_images','order_column','created_at','updated_at'],
    'external_ratings': ['id','restaurant_id','platform','platform_id','rating','review_count',
                         'price_level','platform_url','extra_data','last_synced_at','created_at','updated_at'],
    'restaurant_rankings': ['id','restaurant_id','year','ranking_type','ranking_scope','position',
                            'final_score','score_breakdown','badge_name','certificate_path',
                            'is_published','published_at','created_at','updated_at'],
    'restaurant_scores': ['id','restaurant_id','google_score','yelp_score','facebook_score',
                          'tripadvisor_score','famer_rating_score','review_count_score',
                          'verified_reviews_score','owner_response_score','engagement_score',
                          'subscription_score','seniority_score','survey_score','total_score',
                          'city_rank','state_rank','national_rank','calculated_at','created_at','updated_at'],
    'restaurant_feature': ['restaurant_id','feature_id'],
    'restaurant_food_tag': ['id','restaurant_id','food_tag_id','created_at','updated_at'],
}

def escape_str(val):
    if val is None:
        return 'NULL'
    val = str(val).replace('\\', '\\\\').replace("'", "\\'").replace('\0', '')
    return f"'{val}'"

def format_val(val):
    if val is None:
        return 'NULL'
    if isinstance(val, int):
        return str(val)
    if isinstance(val, float):
        return str(val)
    return escape_str(val)

def main():
    if not os.path.exists(SQLITE_PATH):
        print(f"ERROR: SQLite not found at {SQLITE_PATH}")
        sys.exit(1)

    conn = sqlite3.connect(SQLITE_PATH)
    conn.row_factory = sqlite3.Row

    with open(OUTPUT_SQL, 'w', encoding='utf-8') as f:
        f.write("-- FAMER multi-table migration from SQLite backup\n")
        f.write("-- Generated by migrate_tables_to_mysql.py\n")
        f.write("-- Tables: features, food_tags, users, reviews, media, external_ratings,\n")
        f.write("--         restaurant_rankings, restaurant_scores, restaurant_feature, restaurant_food_tag\n\n")
        f.write("SET NAMES utf8mb4;\n")
        f.write("SET foreign_key_checks = 0;\n\n")

        for table, cols in TABLES.items():
            cursor = conn.cursor()
            cursor.execute(f"SELECT COUNT(*) FROM {table}")
            total = cursor.fetchone()[0]
            print(f"\n{table}: {total:,} rows")

            cols_str = ', '.join(f'`{c}`' for c in cols)
            select_str = ', '.join(f'`{c}`' for c in cols)
            cursor.execute(f"SELECT {select_str} FROM {table} ORDER BY id")

            f.write(f"-- {table} ({total:,} rows)\n")

            batch = []
            rows_written = 0

            for row in cursor:
                values = [format_val(v) for v in row]
                batch.append(f"({', '.join(values)})")
                rows_written += 1

                if len(batch) >= BATCH_SIZE:
                    values_str = ',\n  '.join(batch)
                    f.write(f"INSERT IGNORE INTO `{table}` ({cols_str}) VALUES\n  {values_str};\n")
                    batch = []

            if batch:
                values_str = ',\n  '.join(batch)
                f.write(f"INSERT IGNORE INTO `{table}` ({cols_str}) VALUES\n  {values_str};\n")

            f.write(f"\n")
            print(f"  ✓ {rows_written:,} rows queued")

        f.write("SET foreign_key_checks = 1;\n")

    conn.close()
    size_mb = os.path.getsize(OUTPUT_SQL) / (1024 * 1024)
    print(f"\nOutput: {OUTPUT_SQL} ({size_mb:.1f} MB)")

if __name__ == '__main__':
    main()
